import Navigation from "@/components/Navigation";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full flex flex-col items-center">
          <div className="w-full max-w-[80%] ">
            <Navigation />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
